version: 2

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec

linters-settings:
  govet:
    check-shadowing: true

run:
  timeout: 5m
  tests: true
