# SpecLedger Dependency Manifest v1.0.0
# Generated by sl init on 2026-02-05
# Project: specledger
# Short Code: sl
#
# This project was initialized with SpecLedger
#
# To add dependencies, use:
#   sl deps add git@github.com:org/spec main spec.md --alias alias

